### ISSUE TITLE
Setup and run the Project on PC

### ISSUE THREAD

**Issue by nikolay-eremeev** [nikolay-eremeev/LearningCards#1]
1)Pull project.
2)Adjust settings on your Android Studio, enable developer mode on your phone in order to run dubugging.
3) Connect your phone via USB or create a virtual machine.
4) Put [dctnr.txt](https://github.com/nikolay-eremeev/LearningCards/files/3667490/dctnr.txt) under Downloads on your phone or VM

**Comment by nikolay-eremeev** [comment]
@AurelianLorgar are you there?

**Comment by AurelianLorgar** [comment]
Everything work. Close issue.
